# Nome: Anakin Dantas Rodrigues Matrícula: 2023033173 
# icfis - novembro de 2023

### Atividade 

Encontre as correntes no circuito seguinte, considere as direções iniciais indicadas na figura. 

<img src="Figs/dcp8.gif" width=70% >

Primeria equação:

$$
I_1 + I_2 - I_3 = 0
$$

Segunda e terceira equação (voltagem negativa): 
$$
10I_1 - 10 + 40I_3 = 0 \\
20I_2 - 20 + 40I_3 = 0
$$

In [1]:
import numpy as np

In [2]:
# Solução do sistema de equações encontrado
# no circuito anterior

A = np.array([[1.,1.,-1.],[10.,0.,40.],[0.,20.,40.]])
V = np.array([0.,10.,20.])
I = np.linalg.solve(A,V)

print('as correntes encontradas sao')
print('I_1 =', I[0])
print('I_2 =', I[1])
print('I_3 =', I[2])

as correntes encontradas sao
I_1 = -0.1428571428571427
I_2 = 0.42857142857142866
I_3 = 0.2857142857142857


### Atividade 

Utilize decomposição LU para resolver o sistema de equações derivado para resolver o  problema de mecânica apresentado na figura seguinte, 

<img src="Figs/Image165.gif" width=70% >

Escreva as equações que mantém o sistema estatico, e encontre as forçãs $F_1$, $F_2$ e $F_3$.


Temos as decomposições das forças em x e y e os torques:
$$
\sum F_x = 0 \\
\sum F_y = 0 \\
\sum \tau = 0
$$

Para $\sum F_x = 0$ :

$$
F_1.cos(69.3°) + F_2.cos(71.1°) + F_3.cos(56.6°) = 0
$$

Para $\sum F_y = 0$ :
$$
926 + F_1.sen(69.3°) + F_2.sen(71.1°) + F_3.sen(56.6°) = 0 \\
F_1.sen(69.3°) + F_2.sen(71.1°) + F_3.sen(56.6°) = -926
$$

Para $\sum \tau$ = 0 :

$$
F1.7,80[m].sen(69.3°) + F2.1,50[m].sen(71.1°) + F3.2,60[m].sen(56.6°) + 926.7,80[m].sen(90°) = 0 \\
F1.7,80[m].sen(69.3°) + F2.1,50[m].sen(71.1°) + F3.2,60[m].sen(56.6°) = - 7222,8
$$

In [3]:
import numpy as np
import scipy.linalg

In [4]:
senF1 =  np.sin(69.3*0.0174533)
senF2 =  np.sin(71.1*0.0174533)
senF3 =  np.sin(56.6*0.0174533)

cosF1 =  np.cos(69.3*0.0174533)
cosF2 =  np.cos(71.1*0.0174533)
cosF3 =  np.cos(56.6*0.0174533)
print("Senos: ", "F1:", senF1, "F2:",senF2,"F3:", senF3)
print("Cossenos: ", "F1:", cosF1, "F2:", cosF2, "F3:", cosF3)

Senos:  F1: 0.9354442140597646 F2: 0.94608553109707 F3: 0.8348480963210285
Cossenos:  F1: 0.35347435887502404 F2: 0.3239169150396052 F3: 0.5504803866343966


In [ ]:
# Solução do sistema de equações encontrado

A = np.array([[cosF1, cosF2, cosF3],[senF1, senF2,senF3],[(7.8*senF1),(1.5*senF2),(2.6*senF3)]])
P, L, U = scipy.linalg.lu(A)

In [1]:
n=3
I = np.zeros_like(A)
for i in range (n):
    I[i,i] = 1.

NameError: name 'np' is not defined

In [46]:
LU = scipy.linalg.lu_factor(A)
Ainv = scipy.linalg.lu_solve(LU, I)

In [47]:
np.matmul(A,Ainv)

array([[ 1.00000000e+00,  0.00000000e+00,  1.38777878e-17],
       [-4.44089210e-16,  1.00000000e+00,  2.42861287e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [51]:
LU

(array([[7.29646487, 1.4191283 , 2.17060505],
        [0.12820513, 0.76414601, 0.5565654 ],
        [0.04844461, 0.33392546, 0.25947493]]), array([2, 1, 2], dtype=int32))

In [53]:
Ainv

array([[-0.60054604, -0.05398878,  0.17306752],
       [-2.80701321,  2.2459836 , -0.15196197],
       [ 3.85393692, -1.28692765, -0.02171173]])

In [1]:
A1 = np.array([-0.601,-2.807,3.854])

# Função para multiplicar duas matrizes

def mult_mat(LU,A1):
    # extraimos a dimensão, m x n, da matriz A
    m, n = LU.shape
    # e o numero de colunas da matriz B
    p = A1.shape[1]

    C1 = np.zeros((m,p))

    for i in range(0,m):
        for j in range(0,p):
            for k in range(0,n):
                F1[i,j] += LU[i,k]*A1[k,j] 
    return C1

print("F1 = ", C1[0])

NameError: name 'np' is not defined

In [ ]:
A2 = np.array([-0.054,2.246,-1.287])

# Função para multiplicar duas matrizes

def mult_mat(LU,A2):
    # extraimos a dimensão, m x n, da matriz A
    m, n = LU.shape
    # e o numero de colunas da matriz B
    p = A2.shape[1]

    C2 = np.zeros((m,p))

    for i in range(0,m):
        for j in range(0,p):
            for k in range(0,n):
                C2[i,j] += LU[i,k]*A2[k,j] 
    return C2

print("F1 = ", C2[1])

In [ ]:
A3 = np.array([0.173,-0.152,-0.022])

# Função para multiplicar duas matrizes

def mult_mat(LU,A3):
    # extraimos a dimensão, m x n, da matriz A
    m, n = LU.shape
    # e o numero de colunas da matriz B
    p = A3.shape[1]

    C3 = np.zeros((m,p))

    for i in range(0,m):
        for j in range(0,p):
            for k in range(0,n):
                C3[i,j] += LU[i,k]*A3[k,j] 
    return C3

print("F3 = ", C3[-1])